// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9x8rzZ5yadnojQSbaQKPf-2URkpm9O9A',
    appId: '1:1080800014438:web:f60a3f4f747775080abda7',
    messagingSenderId: '1080800014438',
    projectId: 'reddit-clone-app-d034f',
    authDomain: 'reddit-clone-app-d034f.firebaseapp.com',
    storageBucket: 'reddit-clone-app-d034f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdUElEw6Ez7qM6G0RHW3yyWqzG0xqSn_E',
    appId: '1:1080800014438:android:f145bc618e02f1c80abda7',
    messagingSenderId: '1080800014438',
    projectId: 'reddit-clone-app-d034f',
    storageBucket: 'reddit-clone-app-d034f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUNr060kowIUyRaldXb1qdaoaOkWgp-Q',
    appId: '1:1080800014438:ios:1dc559a1c069b6180abda7',
    messagingSenderId: '1080800014438',
    projectId: 'reddit-clone-app-d034f',
    storageBucket: 'reddit-clone-app-d034f.appspot.com',
    iosClientId: '1080800014438-1v2f75ctao991ar4tn9d5c53lidigbcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );
}
